### POST a race
POST http://127.0.0.1:8080/races
Accept: application/json
Content-Type: application/json

{
  "name": "Pan",
  "location": "Athens",
  "date": "2025-03-09T23:02:31.568395Z",
  "distance_km": 21,
  "elevation_gain": 1000
}

> {% client.global.set("raceId", response.body) %}

### POST a runner
POST http://127.0.0.1:8080/runners
Accept: application/json
Content-Type: application/json

{
  "name": "Panayiotis",
  "email_address": "pkritiotis@gmail.com"
}

> {% client.global.set("runnerId", response.body) %}


### POST result
POST http://127.0.0.1:8080/races/{{raceId}}/results
Accept: application/json
Content-Type: application/json

{
  "runner_id": "{{runnerId}}",
  "race_id": "{{raceId}}",
  "finish_time_ms": 3600000,
  "heart_rate_avg": 150,
  "notes": "Felt good throughout the race"
}

### GET all
GET http://127.0.0.1:8080/races?runner_id={{runnerId}}
Accept: application/json
